Features/results
ttirtia/cod-wz-tournament-web pull request #10
Opened 2021-03-30 20:10 UTC by tblattel

Result input page that also shows last games

2021-03-30 22:30 UTC, ttirtia requested changes
Looking good, just a few things that might be improved a bit.

2021-03-30 22:30 UTC, ttirtia commented on src/components/ResultsInput.vue
> +              </p> -->
Could you clean this up ?

2021-03-30 22:30 UTC, ttirtia commented on src/components/ResultsInput.vue
> +              </p> -->
Same

2021-03-30 22:30 UTC, ttirtia commented on src/components/Tournaments.vue
> +        <!-- <img class="w-min" src="https://via.placeholder.com/150" alt="Mountain"> -->
Yup

2021-03-30 22:30 UTC, ttirtia commented on src/components/Tournaments.vue
> +              <!-- {{tournament.description}} -->
Hum hum

2021-03-30 22:30 UTC, ttirtia commented on src/components/Table.vue
> +        team.players.flat().forEach((player) => {
Is `.flat()` really necessary ? Maybe I'm missing something

2021-03-30 22:30 UTC, ttirtia commented on src/components/Table.vue
> +        return 0;
You might get the same result with `return (a.placement || Number.MAX_SAFE_INTEGER) - (b.placement || Number.MAX_SAFE_INTEGER);`

2021-03-30 22:30 UTC, ttirtia commented on src/layouts/LayoutDefault.vue
> +                      ? 'bg-gray-900 text-white block px-3 py-2 rounded-md text-base font-medium capitalize'
`capitalize` might not be the best choice

2021-03-31 19:23 UTC, tblattel commented on src/components/ResultsInput.vue
> +              </p> -->
done

2021-03-31 19:23 UTC, tblattel commented on src/components/ResultsInput.vue
> +              </p> -->
done

2021-03-31 19:23 UTC, tblattel commented on src/components/Tournaments.vue
> +        <!-- <img class="w-min" src="https://via.placeholder.com/150" alt="Mountain"> -->
done

2021-03-31 19:24 UTC, tblattel commented on src/components/Table.vue
> +        return 0;
Genius.

2021-03-31 20:06 UTC, ttirtia approved these changes
This is wonderful

2021-03-31 20:06 UTC, merged